const allData = [
  [`Recent Repositories`, `最近仓库`],
  [`Search or jump to…`, `搜索并跳转至...`],
  [`Issues`, `问题`],
  [`Pull`, `合并`],
  [`request`, `请求`],
  [`s`, `个`],
  [`Marketplace`, `市场`],
  [`Explore`, `探索`],
  [`Following`, `关注者`],
  [`Find a repository…`, `查找仓库`],
  [`Latest changes`, `最新变化`],
  [`hours ago`, `小时前`],
  [`days ago`, `天前`],
  [`New`, `新建`],
  [`Explore repositories`, `探索存储库`],
  [`Explore more →`, `探索更多 →`],
  [`Set status`, `设置状态`],
  [`Your profile`, `个人信息`],
  [`Your repositories`, `个人仓库`],
  [`Your codespaces`, `你的 codespaces`],
  [`Your projects`, `你的项目`],
  [`Signed in as`, `登陆账户为`],
  [`Feature preview`, `功能预览`],
  [`Upgrade`, `升级`],
  [`Try Enterprise`, `尝试企业版`],
  [`Help`, `帮助`],
  [`Settings`, `设置`],
  [`Sign out`, `退出`],
  [`Overview`, `概述`],
  [`Repositories`, `仓库`],
  [`Projects`, `项目`],
  [`Packages`, `包`],
  [`Popular repositories`, `流行的仓库`],
  [`Edit profile`, `编辑个人信息`],
  [`followers`, ` 被关注`],
  [`following`, ` 关注`],
  [`Public`, `公开`],
  [`Customize your pins`, `定义你的置顶项目`],
  [`Contribution settings`, `贡献设置`],
  [`Pinned`, `置顶`],
  [`Learn how we count contributions`, `了解我们如何计算贡献`],
  [`Code review`, `代码评审`],
  [`Pull requests`, `合并请求`],
  [`Commits`, `提交`],
  [`Contribution activity`, `贡献活动`],
  [`Show more activity`, `显示更多活动`],
  [`Code`, `代码`],
  [`Go to file`, `转至文件`],
  [`Add file`, `添加文件`],
  [`About`, `关于`],
  [`Pin`, `置顶`],
  [`Pin this repository to your profile`, `置顶这个项目到你的个人信息`],
  [`New repository`, `新建仓库`],
  [`Import repository`, `导入仓库`],
  [`New organization`, `新建组织`],
  [`Create a new release`, `创建一个新的版本`],
  [`Publish your first package`, `发布你的第一个包`],
  [`Releases`, `发布`],
  [`Packages `, `包`],
  [`No packages published`, `没有发布任何软件包`],
  [`Languages`, `语言`],
  [`Show more`, `显示更多`],
  [`Recent activity`, `最新动态`],
  [
    `When you take actions across GitHub, we’ll provide links to that activity here.`,
    `当你在 GitHub 上采取行动时，我们会在这里提供该活动的链接。`,
  ],
  [`More`, `更多`],
  [`Subscribe to your news feed`, `订阅你的 feed`],
  [`Blog`, `博客`],
  [`Shop`, `商店`],
  [`Contact GitHub`, `联系 Github`],
  [`Pricing`, `定价`],
  [`Training`, `培训`],
  [`Status`, `状态`],
  [`Security`, `安全`],
  [`Terms`, `团队`],
  [`Privacy`, `隐私`],
  [`Docs`, `文档`],
  [`New project`, `新建项目`],
  [`Activity  overview`, `活动概览`],
  [`Projects`, `项目`],
  [`Security`, `安全`],
  [`Insights`, `统计`],
  [`Create new file`, `创建新的文件`],
  [`Upload files`, `上传文件`],
  [`Code`, `代码`],
  [`Local`, `本地`],
  [`Clone`, `克隆`],
  [`Open with GitHub Desktop`, `在 Github 桌面程序中打开`],
  [`Download ZIP`, `下载压缩包`],
  [`New codespace`, `新建 codespace`],
  [`Less`, `更少`],
  [`Select type`, `选择类型`],
  [`Type`, `类型`],
  [`Language`, `语言`],
  [`Sort`, `排序`],
  [`Private`, `私有`],
  [`Select language`, `选择语言`],
  [`Select order`, `选择顺序`],
  [`Last updated`, `最近更新`],
  [`Create a new repository`, `创建一个新的仓库`],
  [`Owner`, `拥有者`],
  [`Repository name`, `仓库名字`],
  [`Description`, `描述`],
  [`(optional)`, `(可选)`],
  [
    `Anyone on the internet can see this repository. You choose who can commit.`,
    `互联网上的任何人都可以看到这个存储库。你选择谁能够提交。`,
  ],
  [
    `You choose who can see and commit to this repository.`,
    `你可以选择谁可以看到和提交这个版本库。`,
  ],
  [
    `A repository contains all project files, including the revision history. Already have a project repository elsewhere?`,
    `一个仓库包含所有项目文件，包括修订历史。在其他地方已经有一个项目库了？`,
  ],
  [`Import a repository.`, `导入仓库`],
  [
    `Skip this step if you’re importing an existing repository.`,
    `如果你要导入一个已有的版本库，请跳过这一步。`,
  ],
  [
    `Choose which files not to track from a list of templates.`,
    `从一个模板列表中选择哪些文件不需要跟踪。`,
  ],
  [
    `This is where you can write a long description for your project.`,
    `在这里，你可以为你的项目写一个长的描述。`,
  ],
  [
    `A license tells others what they can and can't do with your code.`,
    `许可证告诉别人他们可以和不可以用你的代码做什么。`,
  ],
  [
    `You are creating a public repository in your personal account.`,
    `你正在你的个人账户中创建一个公共库。`,
  ],
  [`Initialize this repository with:`, `用以下方式初始化这个存储库：`],
  [`Create repository`, `创建仓库`],
  [
    `Great repository names are short and memorable. Need inspiration? How about`,
    `伟大的仓库名称是简短而令人难忘的。需要灵感吗？比如 `,
  ],
  [`Your personal account`, `你的个人账户`],
  [`Public profile`, `公开资料`],
  [`Name`, `名字`],
  [`Change username`, `修改用户名`],
  [`Account`, `账户`],
  [`Export account data`, `导出账户数据`],
  [`Appearance`, `外观`],
  [`Accessibility`, `无障碍设施`],
  [`Notifications`, `通知`],
  [`Access`, `访问`],
  [`Personal billing`, `个人帐单`],
  [`Emails`, `邮件`],
  [`Billing and plans`, `账单和计划`],
  [
    `This is a list of SSH keys associated with your account. Remove any keys that you do not recognize.`,
    `这是与你的账户相关的 SSH 密钥的列表，删除任何你不认识的密钥`,
  ],
  [`Organizations`, `组织`],
  [`You are not a member of any organizations.`, `你不是任何组织的成员  `],
  [`Archives`, `归档`],
  [`Security log`, `安全日志`],
  [`Sponsorship log`, `赞助日志`],
  [`No sponsorship activity in this time period`, `这段时间内没有赞助活动`],
  [`Sign in to GitHub`, `登录到 Github`],
  [`Username or email address`, `用户名或邮箱`],
  [`Password`, `密码`],
  [`Sign in`, `登录`],
  [`New to GitHub?`, `刚来 Github？`],
  [`Create an account`, `创建一个账户`],
  [`Forgot password?`, `忘记密码？`],
  [`Create an account`, `创建账户`],
  [
    `Label issues and pull requests for new contributors`,
    `为新的贡献者标记问题和合并请求`,
  ],
  [`Filters`, `过滤`],
  [`New Issue`, `新问题`],
  [`There aren’t any open issues.`, `没有任何公开的问题。`],
  [`Signing in…`, `登录中...`],
  [`Edit repository details`, `编辑仓库详情信息`],
  [`Website`, `网站`],
  [`Cancel`, `取消`],
  [`Save changes`, `保存修改`],
  [`Protect this branch`, `保护这个分支`],
  [`Get started with GitHub Actions`, `开始使用 Github Actions`],
  [
    `Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.`,
    `构建、测试和部署你的代码。使代码审查、分支管理和问题分流以你想要的方式进行。选择一个工作流程来开始。`,
  ],
  [`Browse all categories`, `浏览所有类型`],
  [`Automation`, `自动化`],
  [`Deployment`, `部署`],
  [`Continuous integration`, `持续集成`],
  [`Reporting`, `报告`],
  [`General`, `常规`],
  [`Public email`, `公开的邮箱`],
  [`Bio`, `个人简历`],
  [`URL`, `网站`],
  [`Twitter username`, `Twitter 用户名`],
  [`Company`, `公司`],
  [`Location`, `地址`],
  [`Contributions & Activity`, `贡献和活动`],
  [`Successor settings`, `继承人设置`],
  [`You have not designated a successor.`, `你还没有指定继承人`],
  [`Delete account`, `删除账户`],
  [
    `Once you delete your account, there is no going back. Please be certain.`,
    `一旦你删除了你的账户，就不能够找回了，请慎重`,
  ],
  [`Display current local time`, `显示当前的本地时间`],
  [`Keyboard shortcuts`, `快捷键`],
  [`Subscriptions`, `订阅`],
  [`Verified domains`, `验证的域名`],
  [`There are no verified domains.`, `没有经过验证的域名`],
  [`Password and authentication`, `密码和身份验证`],
  [`Change password`, `修改密码`],
  [`Old password`, `旧密码`],
  [`New password`, `新密码`],
  [`Confirm new password`, `确认新的密码`],
  [`Two-factor authentication`, `两步验证`],
  [`Confirm new password`, `确认新的密码`],
  [`Confirm access`, `确认访问`],
  [`Confirm`, `确认`],
  [`Who has access`, `谁有权限`],
  [`Code and automation`, `代码和自动化`],
  [`Default branch`, `默认分支`],
  [`Branch protection rules`, `分支保护规则`],
  [`Protected tags`, `保护标签`],
  [`Environments`, `环境变量`],
  [`Code security and analysis`, `代码安全性和分析`],
  [`Integrations`, `集成`],
  [`Email notifications`, `邮件通知`],
  [`Collaborators`, `合作者`],
  [`Contributors`, `贡献者`],
  [`Community Standards`, `社区标准`],
  [`Traffic`, `流量`],
  [`Code frequency`, `代码频率`],
  [`Dependency graph`, `依赖图`],
  [`Contributors`, `贡献者`],
  [`You can`, `你可以`],
  [`@mention`, `@`],
  [
    `other users and organizations to link to them.`,
    `其他用户和组织来链接它们`,
  ],
  [`Save`, `保存`],
  [`Cancel`, `取消`],
  [`Welcome to the all-new projects`, `欢迎来到全新的项目`],
  [`No open projects`, `没有开放的项目`],
  [`Add a bio`, `添加个人简介`],
  [`Loading more...`, `正在加载中`],
  [
    `Your popular repositories will now be shown instead of your pins.`,
    `你的热门仓库现在将显示，而不是你的置顶`,
  ],
  [`Unpin`, `不置顶`],
  [`Your pins have been updated.`, `你的置顶已经更新了`],
  [`Advanced search`, `高级搜索`],
  [`Branches`, `分支`],
  [`Social Preview`, `社交预览`],
  [
    `Upload an image to customize your repository’s social media preview.`,
    `上传图片来定制你仓库的社交媒体预览`,
  ],
  [`Pull Requests`, `合并请求`],
  [`Danger Zone`, `危险区`],
  [`Change repository visibility`, `修改仓库的可见性`],
  [`Transfer ownership`, `转让所有权`],
  [`This repository is currently public.`, `这个仓库当前是公开的`],
  [`Archive this repository`, `归档这个仓库`],
  [
    `Mark this repository as archived and read-only.`,
    `将此版本库标记为归档和只读`,
  ],
  [`Delete this repository`, `删除这个仓库`],
  [
    `Once you delete a repository, there is no going back. Please be certain.`,
    `一旦你删除了这个仓库，就不能够撤回了，请确认`,
  ],
  [`Are you absolutely sure?`, `你真的确定吗？`],
  [`Change visibility`, `修改可见性`],
  [`Change to private`, `修改为私有`],
  [`Transfer`, `转移`],
  [`Edit status`, `编辑状态`],
  [`Busy`, `忙`],
  [`Clear status`, `清除状态`],
  [`Never`, `从不`],
  [`Your main branch isn't protected`, `你的 main 分支不是受保护的`],
  [
    `Protect this branch from force pushing or deletion, or require status checks before merging.`,
    `保护这个分支不被强行推送或删减，或要求在合并前进行状态检查 `,
  ],
  [`Learn more`, `学习更多`],
  [`Branch protection rule`, `分支保护规则`],
  [`Protect your most important branches`, `保护你最重要的分支`],
  [`Achievements`, `成就`],
  [`Send feedback`, `发送反馈`],
  [`Choose a license`, `选择许可证`],
  [`Learn more.`, `学习更多`],
  [`Import your project to GitHub`, `导入你得项目到 Github`],
  [`Inbox`, `收件箱`],
  [`Prev`, `上页`],
  [`Next`, `下页`],
  [`Saved`, `保存`],
  [`Done`, `完成`],
  [`Manage notifications`, `管理通知`],
  [`See more`, `查看更多`],
  [`Include in the home page`, `显示在页面上`],
  [`Discussions`, `讨论`],
  [`Users`, `用户`],
  [`This repository is currently private.`, `这个仓库当前是私有的`],
  [`Lists`, `列表`],
  [`Create list`, `创建列表`],
  [`Pushes`, `推送`],
  [
    `Limit how many branches and tags can be updated in a single push`,
    `限制一次推送中可以更新多少个分支和标签`,
  ],
  [`I want to make this repository private`, `我想要让这个仓库变为私有`],
  [`I have read and understand these effects`, `我已经阅读并理解了这些影响`],
  [`New issue`, `新建问题`],
  [`Labels`, `标签`],
  [`New milestone`, `新建里程碑`],
  [`Milestones`, `里程碑`],
  [`You haven’t created any Milestones.`, `你还没有创建任何里程碑。`],
  [`Edit`, `编辑`],
  [`Delete`, `删除`],
  [`Close`, `关闭`],
  [`Success`, `完成`],
  [`Dashboard`, `仪表盘`],
  [`to search`, `搜索`],
  [`Create your first project`, `创建您的第一个项目`],
  [
  `Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.`,
  `准备好开始构建了吗？为新的想法创建一个存储库，或导入一个存储库以继续为它做出贡献。`,
  ],
  [`Filter`, `筛选`],
  [`Events`, `活动`],
  [`Activity you want to see on your feed`, `您希望在推送中看到的活动`],
  [`Stars`, `星`],
  [`main`, `主干`],
  [`Default`, `默认值`],
  [`Tags`, `标签`],
  [`Watch`, `查看`],
  [`Fork`, `复刻`],
  [`Starred`, `标星`],
  [`Switch branches/tags`, `查看所有分支/标签`],
  [`Profile picture`, `简介图片`],
  [`SSH and GPG keys`, `SSH和GPG密钥`],
  [`Cancel changes`, `取消更改`],
  [`Commit changes...`, `提交更改...`],
  [`Platform`, `平台`],
  [`Solutions`, `解决方案`],
  [`Resources`, `资源`],
  [`Open Source`, `开源`],
  [`Sign up`, `注册`],
  [`Enter your email`, `输入你的邮箱`],
  [`Sign up for GitHub`, `注册 GitHub`],
  [`Try GitHub Copilot`, `试用 GitHub Copilot`],
  [`Plan`, `计划`],
  [`Collaborate`, `协作`],
  [`Automate`, `自动化`],
  [`Secure`, `安全`],
  [`Pause`, `暂停`],
  [`Pause animation`, `暂停动画`],
  [`Pause video`, `暂停视频`],
  [`Explore GitHub Copilot`, `探索 GitHub Copilot`],
  [`Read customer story`, `阅读客户案例`],
  [`Read industry report`, `阅读行业报告`],
  [`Automate your path to production`, `自动化您的生产路径`],
  [`Explore GitHub Actions`, `探索 GitHub Actions`],
  [`Code instantly from anywhere`, `随时随地编写代码`],
  [`Keep momentum on the go`, `随时随地保持动力`],
  [`Shape your toolchain`, `塑造您的工具链`],
  [`Explore GitHub Advanced Security`, `探索 GitHub 高级安全`],
  [`Learn about GitHub Code Security`, `了解 GitHub 代码安全`],
  [`Learn about Dependabot`, `了解 Dependabot`],
  [`Learn about GitHub Secret Protection`, `了解 GitHub 密钥保护`],
  [`Explore GitHub Projects`, `探索 GitHub 项目`],
  [`Keep track of your tasks`, `跟踪您的任务`],
  [`Explore GitHub Issues`, `探索 GitHub Issues`],
  [`Share ideas and ask questions`, `分享想法和提问`],
  [`Review code changes together`, `一起审查代码更改`],
  [`Fund open source projects`, `资助开源项目`],
  [`By industry`, `按行业`],
  [`By size`, `按规模`],
  [`By use case`, `按使用场景`],
  [`Explore customer stories`, `探索客户案例`],
  [`View all solutions`, `查看所有解决方案`],
  [`Back to content`, `返回内容`],
  [`Back to top`, `返回顶部`],
  [`Go to GitHub homepage`, `前往 GitHub 首页`],
  [`Subscribe`, `订阅`],
  [`Features`, `功能`],
  [`AI`, `人工智能`],
  [`Roadmap`, `路线图`],
  [`Compare GitHub`, `比较 GitHub`],
  [`Developer API`, `开发者 API`],
  [`Partners`, `合作伙伴`],
  [`Education`, `教育`],
  [`GitHub CLI`, `GitHub 命令行`],
  [`GitHub Desktop`, `GitHub 桌面版`],
  [`GitHub Mobile`, `GitHub 移动版`],
  [`GitHub Marketplace`, `GitHub 市场`],
  [`MCP Registry`, `MCP 注册表`],
  [`Community Forum`, `社区论坛`],
  [`Professional Services`, `专业服务`],
  [`Premium Support`, `高级支持`],
  [`Skills`, `技能`],
  [`About`, `关于`],
  [`Why GitHub`, `为什么选择 GitHub`],
  [`Customer stories`, `客户案例`],
  [`The ReadME Project`, `ReadME 项目`],
  [`Careers`, `招聘`],
  [`Newsroom`, `新闻中心`],
  [`Inclusion`, `包容性`],
  [`Social Impact`, `社会影响力`],
  [`Sitemap`, `网站地图`],
  [`What is Git?`, `什么是 Git？`],
  [`Manage cookies`, `管理 Cookie`],
  [`Do not share my personal information`, `不要分享我的个人信息`],
  [`English`, `英语`],
  [`Select language`, `选择语言`],
  [`Skip to content`, `跳转到内容`],
  [`Homepage`, `首页`],
  [`Contact GitHub Support`, `联系 GitHub 支持`],
  [`Security and quality`, `安全与质量`],
  [`master branch`, `master 分支`],
  [`Go to Branches page`, `前往分支页面`],
  [`Go to Tags page`, `前往标签页面`],
  [`Folders and files`, `文件夹和文件`],
  [`Latest commit`, `最新提交`],
  [`History`, `历史`],
  [`Repository files navigation`, `仓库文件导航`],
  [`Repository files`, `仓库文件`],
  [`Activity`, `活动`],
  [`Report repository`, `报告仓库`],
  [`View license`, `查看许可证`],
  [`License`, `许可证`],
  [`Stars`, `星标`],
  [`Watchers`, `关注者`],
  [`Forks`, `复刻`],
  [`Other`, `其他`],
  [`Community`, `社区`],
  [`Contact`, `联系`],
  [`Footer`, `页脚`],
  [`Footer navigation`, `页脚导航`],
  [`You must be signed in to change notification settings`, `您必须登录才能更改通知设置`],
  [`You must be signed in to star a repository`, `您必须登录才能收藏仓库`],
  [`contributors`, `贡献者`],
  [`The future of building happens together`, `构建的未来是共同创造的`],
  [`GitHub features`, `GitHub 功能`],
  [`GitHub customers`, `GitHub 客户`],
  [`Accelerate your entire workflow`, `加速您的整个工作流程`],
  [`Your AI partner everywhere`, `您无处不在的 AI 伙伴`],
  [`Built-in application security where found means fixed`, `内置应用程序安全，发现即修复`],
  [`Work together, achieve more`, `携手合作，成就更多`],
  [`From startups to enterprises, GitHub scales with teams of any size in any industry`, `从初创公司到企业，GitHub 可随任何行业的任何规模团队扩展`],
  [`Millions of developers and businesses call GitHub home`, `数百万开发者和企业以 GitHub 为家`],
  [`Footnotes`, `脚注`],
  [`Site-wide Links`, `全站链接`],
  [`Subscribe to our developer newsletter`, `订阅我们的开发者通讯`],
  [`Get tips, technical guides, and best practices. Twice a month.`, `获取技巧、技术指南和最佳实践。每月两次。`],
  [`Ecosystem`, `生态系统`],
  [`Support`, `支持`],
  [`Company`, `公司`],
  [`Legal and Resource Links`, `法律和资源链接`],
  [`GitHub's Social Media Links`, `GitHub 的社交媒体链接`],
  [`GitHub on LinkedIn`, `GitHub 在 LinkedIn 上`],
  [`GitHub on Instagram`, `GitHub 在 Instagram 上`],
  [`GitHub on YouTube`, `GitHub 在 YouTube 上`],
  [`GitHub on X`, `GitHub 在 X 上`],
  [`GitHub on TikTok`, `GitHub 在 TikTok 上`],
  [`GitHub on Twitch`, `GitHub 在 Twitch 上`],
  [`GitHub's organization on GitHub`, `GitHub 在 GitHub 上的组织`],
  [`Appearance settings`, `外观设置`],
  [`Code review`, `代码审查`],
  [`Dependency graph`, `依赖图`],
  [`Security debt, solved`, `安全债务，已解决`],
  [`Leverage security campaigns and Copilot Autofix to reduce application vulnerabilities`, `利用安全活动和 Copilot Autofix 减少应用程序漏洞`],
  [`Dependencies you can depend on`, `您可以信赖的依赖项`],
  [`Update vulnerable dependencies with supported fixes for breaking changes`, `使用支持的修复程序更新易受攻击的依赖项以应对重大更改`],
  [`Your secrets, your business`, `您的密钥，您的业务`],
  [`Detect, prevent, and remediate leaked secrets across your organization`, `在整个组织中检测、预防和修复泄露的密钥`],
  [`Apply fixes in seconds`, `几秒钟内应用修复`],
  [`Spend less time debugging and more time building features with Copilot Autofix`, `使用 Copilot Autofix 减少调试时间，将更多时间用于构建功能`],
  [`Copilot Autofix identifies vulnerable code and provides an explanation, together with a secure code suggestion to remediate the vulnerability`, `Copilot Autofix 识别易受攻击的代码并提供解释，以及修复该漏洞的安全代码建议`],
  [`MTTR reduction with Copilot Autofix`, `使用 Copilot Autofix 减少平均修复时间`],
  [`secret leaks stopped in the past 12 months with push protection`, `在过去 12 个月内通过推送保护阻止的密钥泄露`],
  [`GitHub internal customer data`, `GitHub 内部客户数据`],
  [`Plan with clarity`, `清晰规划`],
  [`Organize everything from high-level roadmaps to everyday tasks`, `组织从高级路线图到日常任务的所有内容`],
  [`Create issues and manage projects with tools that adapt to your code`, `使用适应您代码的工具创建议题和管理项目`],
  [`Create space for open-ended conversations alongside your project`, `在项目旁边创建开放式对话空间`],
  [`Assign initial reviews to Copilot for greater speed and quality`, `将初始审查分配给 Copilot 以提高速度和质量`],
  [`Become an open source partner and support the tools and libraries that power your work`, `成为开源合作伙伴，支持为您的工作提供支持的工具和库`],
  [`Figma streamlines development and strengthens security`, `Figma 简化开发并增强安全性`],
  [`Mercedes-Benz standardizes source code and automates onboarding`, `梅赛德斯-奔驰规范源代码并自动化入职流程`],
  [`Mercado Libre cuts coding time by 50%`, `Mercado Libre 将编码时间缩短 50%`],
  [`Duolingo boosts developer speed by 25% with GitHub Copilot`, `Duolingo 使用 GitHub Copilot 将开发者速度提高 25%`],
  [`Gartner Magic Quadrant for AI Code Assistants`, `Gartner AI 代码助手魔力象限`],
  [`Write, test, and fix code quickly with GitHub Copilot, from simple boilerplate to complex features`, `使用 GitHub Copilot 快速编写、测试和修复代码，从简单的样板代码到复杂功能`],
  [`Tools and trends evolve, but collaboration endures`, `工具和趋势在演变，但协作永存`],
  [`With GitHub, developers, agents, and code come together on one platform`, `借助 GitHub，开发者、代理和代码汇聚在一个平台上`],
  [`From your first line of code to final deployment, GitHub provides AI and automation tools to help you build and ship better software faster`, `从第一行代码到最终部署，GitHub 提供 AI 和自动化工具，帮助您更快地构建和交付更好的软件`],
  [`Copilot is ready to work with you at each step of the software development lifecycle`, `Copilot 已准备好在软件开发生命周期的每个步骤与您合作`],
  [`Ship faster with secure, reliable CI/CD`, `通过安全、可靠的 CI/CD 更快地交付`],
  [`Launch a full, cloud-based development environment in seconds`, `在几秒钟内启动完整的基于云的开发环境`],
  [`Manage projects and assign tasks to Copilot, all from your mobile device`, `管理项目并向 Copilot 分配任务，一切都从您的移动设备完成`],
  [`Extend your stack with apps, actions, and AI models`, `使用应用程序、操作和 AI 模型扩展您的技术栈`],
  [`Use AI to find and fix vulnerabilities so your team can ship more secure software faster`, `使用 AI 查找和修复漏洞，让您的团队更快地交付更安全的软件`],
  [`From planning and discussion to code review, GitHub keeps your team's conversation and context next to your code`, `从规划和讨论到代码审查，GitHub 将团队的对话和上下文保存在代码旁边`],
  [`Whether you're scaling your development process or just learning how to code, GitHub is where you belong`, `无论您是在扩展开发流程还是刚刚学习编码，GitHub 都是您的归属`],
  [`Join the world's most widely adopted developer platform to build the technologies that shape tomorrow`, `加入世界上最广泛使用的开发者平台，构建塑造未来的技术`],
  [`Change is constant. GitHub keeps you ahead.`, `变革是永恒的。GitHub 让您保持领先。`],
  [`Linux kernel source tree`, `Linux 内核源代码树`],
];

const MutationObserverConfig = {
  childList: true,
  subtree: true,
  attributeFilter: ["data-label"],
  characterData: true,
};

const observer = new MutationObserver(function (mutations) {
  const treeWalker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ALL,
    {
      acceptNode: function (node) {
        if (
          node.nodeType === 3 ||
          (node.hasAttribute &&
            (node.hasAttribute("data-label") ||
              node.hasAttribute("placeholder") ||
              node.hasAttribute("value")))
        ) {
          return NodeFilter.FILTER_ACCEPT;
        } else {
          return NodeFilter.FILTER_SKIP;
        }
      },
    },
    false
  );
  let dataMap = new Map();
  allData.forEach(([key, val]) => {
    if (key && !dataMap.has(key)) {
      dataMap.set(key, val);
    }
  });
  let currentNode = treeWalker.currentNode;
  while (currentNode) {
    if (currentNode.nodeType === 3) {
      let key1 = currentNode.textContent
        .replace(/^\s*|\s*$/g, "")
        .replace(/\s+/g, " ");
      if (dataMap.has(key1)) currentNode.textContent = dataMap.get(key1);
    } else {
      let key2 = currentNode.getAttribute("data-label");
      if (key2 && dataMap.has(key2))
        currentNode.setAttribute("data-label", dataMap.get(key2));
      let key3 = currentNode.getAttribute("placeholder") || "";
      if ((key3 = key3.trim())) {
        if (dataMap.has(key3))
          currentNode.setAttribute("placeholder", dataMap.get(key3));
      }
      let key4 = currentNode.getAttribute("value");
      if (currentNode.tagName == "INPUT" && dataMap.has(key4)) {
        currentNode.setAttribute("value", dataMap.get(key4));
        let key5 = currentNode.getAttribute("data-signin-label");
        let key6 = currentNode.getAttribute("data-disable-with");
        currentNode.setAttribute("data-signin-label", dataMap.get(key5));
        currentNode.setAttribute("data-disable-with", dataMap.get(key6));
      }
    }
    currentNode = treeWalker.nextNode();
  }
});

observer.observe(document.body, MutationObserverConfig);
