const allData = [
  // === 导航栏 ===
  [`Recent Repositories`, `最近仓库`],
  [`Search or jump to…`, `搜索并跳转至...`],
  [`Marketplace`, `市场`],
  [`Explore`, `探索`],
  [`Following`, `关注者`],
  [`Feature preview`, `功能预览`],
  [`Upgrade`, `升级`],
  [`Try Enterprise`, `尝试企业版`],
  [`Help`, `帮助`],
  [`Settings`, `设置`],
  [`Sign out`, `退出`],
  [`Sign in to GitHub`, `登录到 GitHub`],
  [`Sign in`, `登录`],
  [`New to GitHub?`, `刚来 GitHub？`],
  [`Create an account`, `创建一个账户`],
  [`Forgot password?`, `忘记密码？`],
  [`Username or email address`, `用户名或邮箱`],
  [`Password`, `密码`],
  [`Skip to content`, `跳转到内容`],
  [`Navigation Menu`, `导航菜单`],
  [`Platform`, `平台`],
  [`Solutions`, `解决方案`],
  [`Resources`, `资源`],
  [`Open Source`, `开源`],
  [`Enterprise`, `企业版`],
  [`Pricing`, `定价`],
  [`Sign up for GitHub`, `注册 GitHub`],
  [`Sign up`, `注册`],
  [`Enter your email`, `输入你的邮箱`],
  [`Try GitHub Copilot`, `试试 GitHub Copilot`],
  [`Homepage`, `主页`],
  [`Select language`, `选择语言`],
  [`Back to content`, `返回内容`],
  [`Back to top`, `回到顶部`],
  [`Manage cookies`, `管理 Cookie`],
  [`Do not share my personal information`, `不要共享我的个人信息`],
  [`Subscribe`, `订阅`],

  // === 个人资料页 ===
  [`Overview`, `概述`],
  [`Repositories`, `仓库`],
  [`Projects`, `项目`],
  [`Packages`, `包`],
  [`Popular repositories`, `热门仓库`],
  [`Edit profile`, `编辑个人信息`],
  [`followers`, `关注者`],
  [`following`, `正在关注`],
  [`Public`, `公开`],
  [`Customize your pins`, `自定义你的置顶项目`],
  [`Contribution settings`, `贡献设置`],
  [`Pinned`, `置顶`],
  [`Learn how we count contributions`, `了解我们如何计算贡献`],
  [`Code review`, `代码评审`],
  [`Pull requests`, `合并请求`],
  [`Commits`, `提交`],
  [`Contribution activity`, `贡献活动`],
  [`Show more activity`, `显示更多活动`],
  [`Code`, `代码`],
  [`Stars`, `星标`],
  [`Starred`, `已标星`],
  [`Your profile`, `个人信息`],
  [`Your repositories`, `个人仓库`],
  [`Your codespaces`, `你的 Codespaces`],
  [`Your projects`, `你的项目`],
  [`Signed in as`, `已登录为`],
  [`Find a repository…`, `查找仓库…`],
  [`Latest changes`, `最新变化`],
  [`hours ago`, `小时前`],
  [`days ago`, `天前`],
  [`New`, `新建`],
  [`Explore repositories`, `探索仓库`],
  [`Explore more →`, `探索更多 →`],
  [`Set status`, `设置状态`],
  [`Your popular repositories will now be shown instead of your pins.`, `你的热门仓库现在将显示，而不是你的置顶。`],
  [`Unpin`, `取消置顶`],
  [`Your pins have been updated.`, `你的置顶已更新。`],
  [`Achievements`, `成就`],
  [`Display current local time`, `显示当前本地时间`],
  [`Profile picture`, `头像`],
  [`Block or Report`, `屏蔽或举报`],
  [`Highlight`, `高亮`],
  [`Organizations`, `组织`],
  [`Sponsors`, `赞助者`],

  // === 仓库详情页 ===
  [`Go to file`, `跳转到文件`],
  [`Add file`, `添加文件`],
  [`About`, `关于`],
  [`Pin`, `置顶`],
  [`Pin this repository to your profile`, `将此仓库置顶到你的个人资料`],
  [`New repository`, `新建仓库`],
  [`Import repository`, `导入仓库`],
  [`New organization`, `新建组织`],
  [`Create a new release`, `创建新版本`],
  [`Publish your first package`, `发布你的第一个包`],
  [`Releases`, `版本发布`],
  [`Packages `, `包`],
  [`No packages published`, `没有已发布的包`],
  [`Languages`, `语言`],
  [`Show more`, `显示更多`],
  [`Recent activity`, `最近活动`],
  [`More`, `更多`],
  [`Subscribe to your news feed`, `订阅你的动态`],
  [`Blog`, `博客`],
  [`Shop`, `商店`],
  [`Contact GitHub`, `联系 GitHub`],
  [`Training`, `培训`],
  [`Status`, `状态`],
  [`Security`, `安全`],
  [`Terms`, `条款`],
  [`Privacy`, `隐私`],
  [`Docs`, `文档`],
  [`Activity  overview`, `活动概览`],
  [`Insights`, `洞察`],
  [`Create new file`, `创建新文件`],
  [`Upload files`, `上传文件`],
  [`Local`, `本地`],
  [`Clone`, `克隆`],
  [`Open with GitHub Desktop`, `用 GitHub Desktop 打开`],
  [`Download ZIP`, `下载 ZIP`],
  [`New codespace`, `新建 Codespace`],
  [`Less`, `收起`],
  [`Select type`, `选择类型`],
  [`Type`, `类型`],
  [`Language`, `语言`],
  [`Sort`, `排序`],
  [`Private`, `私有`],
  [`Select order`, `选择排序`],
  [`Last updated`, `最近更新`],
  [`Branches`, `分支`],
  [`Tags`, `标签`],
  [`Watch`, `关注`],
  [`Fork`, `复刻`],
  [`Switch branches/tags`, `切换分支/标签`],
  [`main`, `主分支`],
  [`Default`, `默认`],
  [`Social Preview`, `社交预览`],
  [`Edit repository details`, `编辑仓库详情`],
  [`Website`, `网站`],
  [`Topics`, `话题`],
  [`Create new…`, `新建…`],
  [`Find a topic…`, `查找话题…`],
  [`No topics`, `暂无话题`],
  [`This repository is currently public.`, `此仓库当前为公开状态。`],
  [`This repository is currently private.`, `此仓库当前为私有状态。`],
  [`Watchers`, `关注者`],

  // === 新建仓库 ===
  [`Create a new repository`, `创建新仓库`],
  [`Owner`, `所有者`],
  [`Repository name`, `仓库名称`],
  [`Description`, `描述`],
  [`(optional)`, `（可选）`],
  [
    `Anyone on the internet can see this repository. You choose who can commit.`,
    `互联网上的任何人都可以看到此仓库。你可以选择谁可以提交。`,
  ],
  [
    `You choose who can see and commit to this repository.`,
    `你可以选择谁可以查看和提交此仓库。`,
  ],
  [
    `A repository contains all project files, including the revision history. Already have a project repository elsewhere?`,
    `一个仓库包含所有项目文件，包括修订历史。在其他地方已有项目仓库？`,
  ],
  [`Import a repository.`, `导入仓库。`],
  [
    `Skip this step if you're importing an existing repository.`,
    `如果你要导入已有仓库，请跳过此步骤。`,
  ],
  [
    `Choose which files not to track from a list of templates.`,
    `从模板列表中选择不需要跟踪的文件。`,
  ],
  [
    `This is where you can write a long description for your project.`,
    `在这里你可以为项目编写详细描述。`,
  ],
  [
    `A license tells others what they can and can't do with your code.`,
    `许可证告诉他人他们可以和不能用你的代码做什么。`,
  ],
  [
    `You are creating a public repository in your personal account.`,
    `你正在个人账户中创建公开仓库。`,
  ],
  [`Initialize this repository with:`, `用以下方式初始化此仓库：`],
  [`Create repository`, `创建仓库`],
  [
    `Great repository names are short and memorable. Need inspiration? How about`,
    `好的仓库名称简短易记。需要灵感吗？试试`,
  ],
  [`Add a README file`, `添加 README 文件`],
  [`Add a .gitignore`, `添加 .gitignore`],
  [`Choose a license`, `选择许可证`],

  // === Issue 页面 ===
  [`Issues`, `议题`],
  [`Pull`, `拉取`],
  [`request`, `请求`],
  [`s`, `s`],
  [`Filters`, `筛选`],
  [`New Issue`, `新建议题`],
  [`There aren't any open issues.`, `没有打开的议题。`],
  [`New issue`, `新建议题`],
  [`Labels`, `标签`],
  [`Milestones`, `里程碑`],
  [`New milestone`, `新建里程碑`],
  [`You haven't created any Milestones.`, `你还没有创建任何里程碑。`],
  [`Label issues and pull requests for new contributors`, `为新贡献者标记议题和合并请求`],
  [`Open`, `打开`],
  [`Closed`, `已关闭`],
  [`Merged`, `已合并`],
  [`Author`, `作者`],
  [`Newest`, `最新`],
  [`Oldest`, `最早`],
  [`Most commented`, `评论最多`],
  [`Least commented`, `评论最少`],
  [`Recently updated`, `最近更新`],
  [`Least recently updated`, `最久未更新`],
  [`No results matched your search.`, `没有与你的搜索匹配的结果。`],
  [`Clear filters`, `清除筛选`],
  [`Clear current search query, filters, and sorts`, `清除当前搜索查询、筛选和排序`],
  [`Assignees`, `指派给`],
  [`No one assigned`, `未指派`],
  [`No projects`, `暂无项目`],
  [`Mark as duplicate`, `标记为重复`],
  [`You're receiving notifications because you're subscribed to this thread.`, `你正在接收通知，因为你订阅了此对话。`],
  [`Mute this conversation`, `静音此对话`],
  [`Copy link`, `复制链接`],
  [`Quote reply`, `引用回复`],
  [`Reference in new issue`, `在新议题中引用`],
  [`Add your reaction`, `添加你的反应`],
  [`Comment`, `评论`],
  [`Write`, `编写`],
  [`Preview`, `预览`],
  [`Submit`, `提交`],
  [`Leave a comment`, `留下评论`],
  [`Adding labels`, `添加标签`],
  [`Searching`, `搜索中`],
  [`Pull Requests`, `合并请求`],
  [`Conversation`, `对话`],
  [`Checks`, `检查`],
  [`Files changed`, `文件变更`],
  [`Reviewers`, `审查者`],
  [`Review required`, `需要审查`],
  [`Changes approved`, `变更已批准`],
  [`Changes requested`, `已请求变更`],
  [`Approve`, `批准`],
  [`Request changes`, `请求变更`],
  [`Leave review`, `离开审查`],
  [`Revert`, `还原`],
  [`Merge pull request`, `合并拉取请求`],
  [`Squash and merge`, `压缩合并`],
  [`Rebase and merge`, `变基合并`],
  [`Create a merge commit`, `创建合并提交`],
  [`Merge`, `合并`],
  [`Close pull request`, `关闭合并请求`],
  [`Reopen pull request`, `重新打开合并请求`],
  [`Delete branch`, `删除分支`],
  [`View file`, `查看文件`],
  [`View diff`, `查看差异`],
  [`Hide whitespace`, `隐藏空白字符`],
  [`Show whitespace`, `显示空白字符`],
  [`Split`, `拆分`],
  [`Unified`, `统一`],
  [`Add your review`, `添加你的审查`],
  [`Review changes`, `审查变更`],
  [`Single comment`, `单条评论`],
  [`Start a review`, `开始审查`],
  [`Resolve conversation`, `解决对话`],
  [`Outdated`, `已过期`],
  [`Loading`, `加载中`],
  [`Checking…`, `检查中…`],
  [`All checks have passed`, `所有检查已通过`],
  [`Some checks have failed`, `部分检查未通过`],
  [`All checks were successful`, `所有检查均成功`],
  // === 仓库设置 ===
  [`Danger Zone`, `危险区域`],
  [`Change repository visibility`, `更改仓库可见性`],
  [`Transfer ownership`, `转移所有权`],
  [`Archive this repository`, `归档此仓库`],
  [`Delete this repository`, `删除此仓库`],
  [`Are you absolutely sure?`, `你确定吗？`],
  [`Change visibility`, `更改可见性`],
  [`Change to private`, `更改为私有`],
  [`Transfer`, `转移`],
  [`Archive`, `归档`],
  [
    `Mark this repository as archived and read-only.`,
    `将此仓库标记为已归档和只读。`,
  ],
  [`I want to make this repository private`, `我想将此仓库设为私有`],
  [`I have read and understand these effects`, `我已阅读并理解这些影响`],
  [`General`, `常规`],
  [`Rename`, `重命名`],
  [`Require issues and pull requests to have a title`, `要求议题和合并请求必须有标题`],
  [`Require commits to be signed`, `要求提交必须签名`],
  [`Wikis`, `Wiki`],
  [`Features`, `功能`],
  [`Branch protection rules`, `分支保护规则`],
  [`Branch protection rule`, `分支保护规则`],
  [`Protect your most important branches`, `保护你最重要的分支`],
  [`Protect this branch`, `保护此分支`],
  [`Your main branch isn't protected`, `你的 main 分支未受保护`],
  [
    `Protect this branch from force pushing or deletion, or require status checks before merging.`,
    `保护此分支免受强制推送或删除，或要求合并前通过状态检查。`,
  ],
  [`Protected tags`, `受保护的标签`],
  [`Limit how many branches and tags can be updated in a single push`, `限制单次推送中可更新的分支和标签数量`],

  // === 仓库 Insights ===
  [`Pulse`, `动态`],
  [`Contributors`, `贡献者`],
  [`Community`, `社区`],
  [`Community Standards`, `社区标准`],
  [`Traffic`, `流量`],
  [`Code frequency`, `代码频率`],
  [`Dependency graph`, `依赖图`],
  [`Network`, `网络`],
  [`Clones`, `克隆`],
  [`Popular content`, `热门内容`],
  [`Top paths`, `热门路径`],
  [`Top referrers`, `热门来源`],
  [`Search engines`, `搜索引擎`],
  [`Domains`, `域名`],
  [`Views`, `浏览量`],
  [`Unique visitors`, `独立访客`],

  // === 用户设置 ===
  [`Your personal account`, `你的个人账户`],
  [`Public profile`, `公开资料`],
  [`Name`, `姓名`],
  [`Change username`, `修改用户名`],
  [`Account`, `账户`],
  [`Export account data`, `导出账户数据`],
  [`Appearance`, `外观`],
  [`Accessibility`, `无障碍`],
  [`Notifications`, `通知`],
  [`Access`, `访问权限`],
  [`Personal billing`, `个人账单`],
  [`Emails`, `邮箱`],
  [`Billing and plans`, `账单和方案`],
  [`SSH and GPG keys`, `SSH 和 GPG 密钥`],
  [`Password and authentication`, `密码和身份验证`],
  [`Change password`, `修改密码`],
  [`Old password`, `旧密码`],
  [`New password`, `新密码`],
  [`Confirm new password`, `确认新密码`],
  [`Two-factor authentication`, `双因素认证`],
  [`Confirm access`, `确认访问`],
  [`Confirm`, `确认`],
  [`Who has access`, `谁有访问权限`],
  [`Code and automation`, `代码与自动化`],
  [`Default branch`, `默认分支`],
  [`Environments`, `环境`],
  [`Code security and analysis`, `代码安全与分析`],
  [`Integrations`, `集成`],
  [`Email notifications`, `邮件通知`],
  [`Collaborators`, `协作者`],
  [`You can`, `你可以`],
  [`@mention`, `@提及`],
  [
    `other users and organizations to link to them.`,
    `其他用户和组织来链接他们。`,
  ],
  [`Cancel`, `取消`],
  [`Bio`, `个人简介`],
  [`URL`, `网址`],
  [`Company`, `公司`],
  [`Location`, `所在地`],
  [`Twitter username`, `Twitter 用户名`],
  [`Add a bio`, `添加简介`],
  [`Contributions & Activity`, `贡献和活动`],
  [`Successor settings`, `继任者设置`],
  [`You have not designated a successor.`, `你还没有指定继任者。`],
  [`Delete account`, `删除账户`],
  [
    `Once you delete your account, there is no going back. Please be certain.`,
    `一旦你删除账户，就无法恢复。请慎重操作。`,
  ],
  [`Keyboard shortcuts`, `快捷键`],
  [`Subscriptions`, `订阅`],
  [`Verified domains`, `已验证域名`],
  [`There are no verified domains.`, `没有已验证的域名。`],
  [
    `This is a list of SSH keys associated with your account. Remove any keys that you do not recognize.`,
    `这是与你的账户关联的 SSH 密钥列表。请删除你不认识的密钥。`,
  ],
  [`You are not a member of any organizations.`, `你不是任何组织的成员。`],
  [`Archives`, `归档`],
  [`Security log`, `安全日志`],
  [`Sponsorship log`, `赞助日志`],
  [`No sponsorship activity in this time period`, `此时间段内没有赞助活动`],

  // === Projects ===
  [`New project`, `新建项目`],
  [`Welcome to the all-new projects`, `欢迎使用全新的项目`],
  [`No open projects`, `没有打开的项目`],
  [`Create your first project`, `创建你的第一个项目`],
  [
    `Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.`,
    `准备好开始构建了吗？为新想法创建仓库，或将已有仓库导入以继续贡献。`,
  ],

  // === Discussions ===
  [`Discussions`, `讨论`],
  [`Categories`, `分类`],
  [`Start a new discussion`, `开始新讨论`],
  [`Upvotes`, `赞`],
  [`No replies`, `暂无回复`],
  [`Reply`, `回复`],

  // === Actions ===
  [`Get started with GitHub Actions`, `开始使用 GitHub Actions`],
  [
    `Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.`,
    `构建、测试和部署你的代码。使代码审查、分支管理和议题分流按你的方式进行。选择一个工作流开始。`,
  ],
  [`Browse all categories`, `浏览所有类别`],
  [`Automation`, `自动化`],
  [`Deployment`, `部署`],
  [`Continuous integration`, `持续集成`],
  [`Reporting`, `报告`],
  [`Workflows`, `工作流`],
  [`Workflow runs`, `工作流运行`],
  [`Run workflow`, `运行工作流`],
  [`Enable workflows`, `启用工作流`],
  [`Disable workflows`, `禁用工作流`],
  [`All workflows`, `所有工作流`],
  [`Active workflows`, `活跃的工作流`],
  [`Disabled workflows`, `已禁用的工作流`],
  [`Learn more`, `了解更多`],
  [`Learn more.`, `了解更多。`],
  [`Success`, `成功`],
  [`Failure`, `失败`],
  [`In progress`, `进行中`],
  [`Queued`, `排队中`],
  [`Skipped`, `已跳过`],
  [`Cancelled`, `已取消`],
  [`Approved`, `已批准`],
  [`Rejected`, `已拒绝`],
  [`Review`, `审查`],
  [`Rerun`, `重新运行`],
  [`Rerun all failed jobs`, `重新运行所有失败的作业`],
  [`Rerun all jobs`, `重新运行所有作业`],
  [`Cancel workflow run`, `取消工作流运行`],
  [`Delete workflow run`, `删除工作流运行`],
  [`Approve workflow run`, `批准工作流运行`],
  [`View run`, `查看运行`],
  [`View workflow`, `查看工作流`],
  [`Use workflow`, `使用工作流`],
  [`Jobs`, `作业`],
  [`Steps`, `步骤`],
  [`Artifacts`, `制品`],
  [`Usage`, `用量`],
  [`Environment`, `环境`],
  [`Trigger`, `触发器`],
  [`Run name`, `运行名称`],
  [`This workflow has a workflow_dispatch event trigger.`, `此工作流有 workflow_dispatch 事件触发器。`],
  [`Use workflow from`, `使用来自以下位置的工作流`],
  [`Create new file`, `创建新文件`],
  [`Set up a workflow yourself`, `自己设置工作流`],
  [`See more`, `查看更多`],

  // === Wiki ===
  [`Wiki`, `Wiki`],
  [`Create the first page`, `创建第一个页面`],
  [`Create a new page`, `创建新页面`],
  [`Edit this page`, `编辑此页面`],
  [`Delete this page`, `删除此页面`],
  [`Page history`, `页面历史`],
  [`Last edited by`, `最后编辑者`],
  [`Pages`, `页面`],

  // === 通知 ===
  [`Inbox`, `收件箱`],
  [`Manage notifications`, `管理通知`],
  [`Saved`, `已保存`],
  [`Done`, `完成`],
  [`Mark all as read`, `全部标记为已读`],
  [`Mark as read`, `标记为已读`],
  [`Mark as unread`, `标记为未读`],
  [`Unread`, `未读`],
  [`Participating`, `参与的`],
  [`All`, `全部`],
  [`Reason`, `原因`],
  [`Repository`, `仓库`],
  [`Mute`, `静音`],
  [`Unmute`, `取消静音`],
  [`Previous`, `上一条`],
  [`Next`, `下一条`],
  [`Mark as done`, `标记为已完成`],
  [`You have no unread notifications.`, `你没有未读通知。`],
  [`Participating and @mentions`, `参与的及 @提及`],

  // === 安全页面 ===
  [`Code scanning`, `代码扫描`],
  [`Secret scanning`, `密钥扫描`],
  [`Dependabot`, `Dependabot`],
  [`Dependabot alerts`, `Dependabot 警报`],
  [`Dependabot security updates`, `Dependabot 安全更新`],
  [`Alert`, `警报`],
  [`Alerts`, `警报`],
  [`Severity`, `严重程度`],
  [`CVSS`, `CVSS`],
  [`Tool`, `工具`],
  [`Dismiss`, `忽略`],
  [`Dismiss alert`, `忽略警报`],
  [`Resolve`, `解决`],
  [`Auto-fixed`, `已自动修复`],
  [`View details`, `查看详情`],
  [`No alerts found`, `未发现警报`],
  [`Push protection`, `推送保护`],
  [`Secrets`, `密钥`],
  [`Custom patterns`, `自定义模式`],
  [`Allow specified patterns`, `允许指定模式`],

  // === 搜索 ===
  [`Search`, `搜索`],
  [`to search`, `搜索`],
  [`Advanced search`, `高级搜索`],
  [`Search all of GitHub`, `搜索整个 GitHub`],
  [`Filter by language`, `按语言筛选`],
  [`Filter by`, `按以下条件筛选`],
  [`Sort by`, `按以下方式排序`],
  [`No results found`, `未找到结果`],
  [`Tip:`, `提示：`],
  [`You can also search for`, `你也可以搜索`],

  // === 时间相关 ===
  [`minutes ago`, `分钟前`],
  [`weeks ago`, `周前`],
  [`months ago`, `个月前`],
  [`years ago`, `年前`],
  [`just now`, `刚刚`],
  [`yesterday`, `昨天`],
  [`today`, `今天`],
  [`last week`, `上周`],
  [`last month`, `上个月`],
  [`on`, `在`],
  [`Loading more...`, `正在加载更多...`],
  [`Loading...`, `加载中...`],
  [`Signing in…`, `登录中…`],

  // === 通用按钮和操作 ===
  [`Edit`, `编辑`],
  [`Delete`, `删除`],
  [`Close`, `关闭`],
  [`Save`, `保存`],
  [`Save changes`, `保存更改`],
  [`Cancel changes`, `取消更改`],
  [`Commit changes...`, `提交更改…`],
  [`Copy`, `复制`],
  [`Copied!`, `已复制！`],
  [`Share`, `分享`],
  [`Report`, `举报`],
  [`Block`, `屏蔽`],
  [`Follow`, `关注`],
  [`Unfollow`, `取消关注`],
  [`Subscribe`, `订阅`],
  [`Include in the home page`, `显示在主页上`],
  [`Show more`, `显示更多`],
  [`Show less`, `收起`],
  [`Show all`, `显示全部`],
  [`Collapse`, `折叠`],
  [`Expand`, `展开`],
  [`Refresh`, `刷新`],
  [`Retry`, `重试`],
  [`Apply`, `应用`],
  [`Continue`, `继续`],
  [`Skip`, `跳过`],
  [`Finish`, `完成`],
  [`OK`, `确定`],
  [`Yes`, `是`],
  [`No`, `否`],
  [`Send feedback`, `发送反馈`],
  [`Learn more`, `了解更多`],
  [`Learn more.`, `了解更多。`],
  [`Read more`, `阅读更多`],
  [`View all`, `查看全部`],
  [`Show details`, `显示详情`],
  [`Hide details`, `隐藏详情`],
  [`Options`, `选项`],
  [`Actions`, `操作`],
  [`Select`, `选择`],
  [`Deselect all`, `取消全选`],
  [`Select all`, `全选`],
  [`Remove`, `移除`],
  [`Restore`, `恢复`],
  [`Download`, `下载`],
  [`Upload`, `上传`],
  [`Import`, `导入`],
  [`Export`, `导出`],
  [`Print`, `打印`],

  // === 404 / 错误页面 ===
  [`Page not found`, `页面未找到`],
  [`Something went wrong`, `出了点问题`],
  [`Try again`, `重试`],
  [`Go back`, `返回`],
  [`Go home`, `回到首页`],

  // === 用户列表和组织 ===
  [`Users`, `用户`],
  [`Lists`, `列表`],
  [`Create list`, `创建列表`],
  [`Members`, `成员`],
  [`Teams`, `团队`],
  [`People`, `成员`],
  [`Add a member`, `添加成员`],
  [`Invite`, `邀请`],
  [`Remove member`, `移除成员`],

  // === 活动记录 ===
  [`Events`, `事件`],
  [`Filter`, `筛选`],
  [`Activity you want to see on your feed`, `你想在动态中看到的活动`],
  [`Pushes`, `推送`],
  [`Pull request`, `合并请求`],
  [`Release`, `版本发布`],
  [`Comments`, `评论`],
  [`Reactions`, `反应`],
  [`New member`, `新成员`],
  [`New team`, `新团队`],
  [`New issue`, `新议题`],
  [`Deleted`, `已删除`],
  [`Created`, `已创建`],
  [`Published`, `已发布`],

  // === Trending / 发现 ===
  [`Trending`, `趋势`],
  [`Trending repositories`, `热门仓库`],
  [`Trending developers`, `热门开发者`],
  [`Daily`, `每日`],
  [`Weekly`, `每周`],
  [`Monthly`, `每月`],
  [`Stars today`, `今日星标`],
  [`Stars this week`, `本周星标`],
  [`Stars this month`, `本月星标`],
  [`Built by`, `构建者`],
  [`Star`, `星标`],

  // === 仓库模板 ===
  [`Import your project to GitHub`, `将你的项目导入 GitHub`],
  [`Explore GitHub`, `探索 GitHub`],
  [`GitHub Marketplace`, `GitHub 市场`],
  [`GitHub Sponsors`, `GitHub 赞助`],
  [`GitHub CLI`, `GitHub CLI`],
  [`GitHub Desktop`, `GitHub 桌面版`],
  [`GitHub Mobile`, `GitHub 移动端`],
  [`GitHub Pages`, `GitHub Pages`],
  [`GitHub Codespaces`, `GitHub Codespaces`],
  [`GitHub Copilot`, `GitHub Copilot`],
  [`GitHub Advanced Security`, `GitHub 高级安全`],
  [`Developer API`, `开发者 API`],
  [`Partners`, `合作伙伴`],
  [`Education`, `教育`],
  [`Roadmap`, `路线图`],
  [`Compare GitHub`, `对比 GitHub`],
  [`Why GitHub`, `为什么选择 GitHub`],
  [`Customer stories`, `客户故事`],
  [`The ReadME Project`, `The ReadME 项目`],
  [`Careers`, `招聘`],
  [`Newsroom`, `新闻室`],
  [`Social Impact`, `社会影响`],
  [`Community Forum`, `社区论坛`],
  [`Professional Services`, `专业服务`],
  [`Premium Support`, `高级支持`],
  [`Skills`, `技能`],
  [`About`, `关于`],
  [`Subscribe to our developer newsletter`, `订阅我们的开发者通讯`],
  [`Get tips, technical guides, and best practices. Twice a month.`, `获取技巧、技术指南和最佳实践。每月两次。`],
  [`Legal and Resource Links`, `法律和资源链接`],
  [`What is Git?`, `什么是 Git？`],
  [`Sitemap`, `网站地图`],
  [`GitHub's Social Media Links`, `GitHub 社交媒体链接`],

  // === 文件浏览器 ===
  [`Go to line`, `跳转到行`],
  [`Find in file`, `在文件中查找`],
  [`Blame`, `追溯`],
  [`Raw`, `原始文件`],
  [`Copy raw contents`, `复制原始内容`],
  [`Copy permalink`, `复制永久链接`],
  [`View blame prior to this change`, `查看此变更前的追溯`],
  [`Delete file`, `删除文件`],
  [`Edit file`, `编辑文件`],
  [`This file was deleted.`, `此文件已被删除。`],
  [`File renamed without changes.`, `文件已重命名，无内容变更。`],
  [`Binary file not shown.`, `二进制文件未显示。`],
  [`File too large to display`, `文件太大，无法显示`],

  // === Gist ===
  [`Gist`, `Gist`],
  [`All gists`, `所有 Gist`],
  [`My gists`, `我的 Gist`],
  [`Create a gist`, `创建 Gist`],
  [`Name your gist`, `为你的 Gist 命名`],
  [`Description optional`, `描述（可选）`],
  [`Make secret`, `设为私密`],
  [`Create public gist`, `创建公开 Gist`],
  [`Create secret gist`, `创建私密 Gist`],
  [`Secret`, `私密`],
  [`Public`, `公开`],
  [`Embed`, `嵌入`],
  [`Embed this gist`, `嵌入此 Gist`],
  [`Clone via HTTPS`, `通过 HTTPS 克隆`],
  [`Clone with an SSH key`, `使用 SSH 密钥克隆`],
  [`Clone with the CLI`, `使用 CLI 克隆`],
  [`Use Git or checkout with SVN using the web URL.`, `使用 Git 或通过 SVN 使用网页 URL 检出。`],
  [`HTTPS`, `HTTPS`],
  [`SSH`, `SSH`],
  [`GitHub CLI`, `GitHub CLI`],
  [`Copy`, `复制`],
  [`Open in Desktop`, `在桌面端打开`],
  [`Download ZIP`, `下载 ZIP`],

  // === Copilot 相关 ===
  [`Copilot`, `Copilot`],
  [`Ask Copilot`, `问 Copilot`],
  [`Copilot Chat`, `Copilot 聊天`],
  [`Copilot for Business`, `Copilot 商业版`],
  [`Copilot for Individuals`, `Copilot 个人版`],
  [`Try GitHub Copilot`, `试试 GitHub Copilot`],
  [`Explore GitHub Copilot`, `探索 GitHub Copilot`],

  // === Codespaces ===
  [`Your codespaces`, `你的 Codespaces`],
  [`Create new codespace`, `创建新 Codespace`],
  [`No codespaces yet`, `暂无 Codespaces`],
  [`Open in browser`, `在浏览器中打开`],
  [`Open in VS Code`, `在 VS Code 中打开`],
  [`Open in JetBrains`, `在 JetBrains 中打开`],

  // === GitHub Pages ===
  [`Build and deployment`, `构建和部署`],
  [`Source`, `来源`],
  [`Branch`, `分支`],
  [`Folder`, `文件夹`],
  [`Custom domain`, `自定义域名`],
  [`Your site is live at`, `你的网站已上线，地址为`],
  [`Visit site`, `访问网站`],

  // === 仓库设置页详细项 ===
  [`Manage access`, `管理访问权限`],
  [`Add people`, `添加人员`],
  [`Invite a collaborator`, `邀请协作者`],
  [`Teams`, `团队`],
  [`Outside collaborators`, `外部协作者`],

  // === 通用提示文本 ===
  [
    `When you take actions across GitHub, we'll provide links to that activity here.`,
    `当你在 GitHub 上进行操作时，我们会在此处提供相关活动的链接。`,
  ],
  [`Dashboard`, `仪表盘`],
  [`All activity`, `所有活动`],
  [`Repositories you contribute to`, `你贡献的仓库`],
  [`Your activity`, `你的活动`],
  [`News feed`, `新闻动态`],
  [`Your teams`, `你的团队`],
  [`All GitHub`, `整个 GitHub`],
  [`Trending`, `趋势`],
  [`Collections`, `收藏集`],
  [`GitHub Sponsors`, `GitHub 赞助`],
  [`Title`, `标题`],
  [`Title is required`, `标题为必填项`],
  [`Comment body is required.`, `评论内容为必填项。`],
  [`Submit new issue`, `提交新议题`],
  [`Attach images by dragging & dropping, selecting or pasting them.`, `通过拖放、选择或粘贴来添加图片。`],
  [`Write a comment`, `写评论`],
  [`Submit review`, `提交审查`],
  [`Approve`, `批准`],
  [`Add single comment`, `添加单条评论`],
  [`File`, `文件`],
  [`Create new file`, `创建新文件`],
  [`Update file`, `更新文件`],
  [`Replace`, `替换`],
  [`Commit summary`, `提交摘要`],
  [`Optional extended description`, `可选的详细描述`],
  [`Commit directly to the`, `直接提交到`],
  [`branch`, `分支`],
  [`Create a new branch`, `创建新分支`],
  [`for this commit and start a pull request.`, `并以此提交开始合并请求。`],
  [`Propose changes`, `提议更改`],
  [`Changes`, `更改`],
  [`Additions`, `新增`],
  [`Deletions`, `删除`],
  [`Showing`, `显示`],
  [`changed files`, `个变更文件`],
  [`with`, `含`],
  [`additions`, `项新增`],
  [`and`, `和`],
  [`deletions`, `项删除`],

  // === Readme 编辑器 ===
  [`Edit`, `编辑`],
  [`No description, website, or topics provided.`, `暂无描述、网站或话题。`],
  [`README`, `README`],

  // === Release 页面 ===
  [`Latest release`, `最新版本`],
  [`Tags`, `标签`],
  [`Draft`, `草稿`],
  [`Prerelease`, `预发布`],
  [`Latest`, `最新`],
  [`Compare`, `对比`],
  [`Assets`, `资源`],
  [`Source code`, `源代码`],
  [`zip`, `zip`],
  [`tar.gz`, `tar.gz`],

  // === 网络页面 ===
  // === 通用杂项 ===
];

const MutationObserverConfig = {
  childList: true,
  subtree: true,
  attributeFilter: ["data-label"],
  characterData: true,
};

const observer = new MutationObserver(function (mutations) {
  const treeWalker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ALL,
    {
      acceptNode: function (node) {
        if (
          node.nodeType === 3 ||
          (node.hasAttribute &&
            (node.hasAttribute("data-label") ||
              node.hasAttribute("placeholder") ||
              node.hasAttribute("value")))
        ) {
          return NodeFilter.FILTER_ACCEPT;
        } else {
          return NodeFilter.FILTER_SKIP;
        }
      },
    },
    false
  );
  let dataMap = new Map();
  allData.forEach(([key, val]) => {
    if (key && !dataMap.has(key)) {
      dataMap.set(key, val);
    }
  });
  let currentNode = treeWalker.currentNode;
  while (currentNode) {
    if (currentNode.nodeType === 3) {
      let key1 = currentNode.textContent
        .replace(/^\s*|\s*$/g, "")
        .replace(/\s+/g, " ");
      if (dataMap.has(key1)) currentNode.textContent = dataMap.get(key1);
    } else {
      let key2 = currentNode.getAttribute("data-label");
      if (key2 && dataMap.has(key2))
        currentNode.setAttribute("data-label", dataMap.get(key2));
      let key3 = currentNode.getAttribute("placeholder") || "";
      if ((key3 = key3.trim())) {
        if (dataMap.has(key3))
          currentNode.setAttribute("placeholder", dataMap.get(key3));
      }
      let key4 = currentNode.getAttribute("value");
      if (currentNode.tagName == "INPUT" && dataMap.has(key4)) {
        currentNode.setAttribute("value", dataMap.get(key4));
        let key5 = currentNode.getAttribute("data-signin-label");
        let key6 = currentNode.getAttribute("data-disable-with");
        currentNode.setAttribute("data-signin-label", dataMap.get(key5));
        currentNode.setAttribute("data-disable-with", dataMap.get(key6));
      }
    }
    currentNode = treeWalker.nextNode();
  }
});

observer.observe(document.body, MutationObserverConfig);
